DATA SCORE_LIST;
INPUT SCHOOL $ MATH_BEFORE MATH_AFTER @@;
MATH_IMPROVE= MATH_AFTER - MATH_BEFORE;
DATALINES;
UC 80 81 UC 80 80 UC 90 87
OSU 70 80 OSU 78 80
RUN;

RUN;
PROC PRINT DATA=SCORE_LIST;
RUN;

DATA LIST_NEW;
	set SCORE_LIST;
KEEP SCHOOL MATH_IMPROVE;
RUN;
PROC SORT DATA=LIST_NEW OUT=LIST2;
 BY MATH_IMPROVE;
DATA LIST2;
SET LIST2;
IF MATH_IMPROVE >0 THEN GOOD='YES';
 ELSE GOOD='NO';
RUN;
PROC PRINT DATA=LIST2;
RUN;